/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.63).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Actor;
import io.swagger.model.Film;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2024-10-16T13:57:59.465281663Z[GMT]")
@Validated
public interface ActorsApi {

    @Operation(summary = "Remove a specific Actor.", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "204", description = "Actor removed with successfully"),
        
        @ApiResponse(responseCode = "404", description = "Actor not found") })
    @RequestMapping(value = "/actors/{actorId}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> actorsActorIdDelete(@Parameter(in = ParameterIn.PATH, description = "Actor's ID", required=true, schema=@Schema()) @PathVariable("actorId") Integer actorId
);


    @Operation(summary = "Add a new actor", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Actor created with successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Actor.class))) })
    @RequestMapping(value = "/actors",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Actor> createActor(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Actor body
);


    @Operation(summary = "gets a specific actor", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Actor details", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Actor.class))),
        
        @ApiResponse(responseCode = "404", description = "Actor not found") })
    @RequestMapping(value = "/actors/{actorId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Actor> getActorById(@Parameter(in = ParameterIn.PATH, description = "Actor's ID", required=true, schema=@Schema()) @PathVariable("actorId") Integer actorId
);


    @Operation(summary = "gets all actors", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "List of actors", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Actor.class)))) })
    @RequestMapping(value = "/actors",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Actor>> getActors();


    @Operation(summary = "gets all film of specific actor", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "List of films the actor has performed in", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Film.class)))),
        
        @ApiResponse(responseCode = "404", description = "Actor or films not found") })
    @RequestMapping(value = "/actors/{actorId}/films",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Film>> getFilmsByActor(@Parameter(in = ParameterIn.PATH, description = "Actor's ID", required=true, schema=@Schema()) @PathVariable("actorId") Integer actorId
);


    @Operation(summary = "Update all details about actor", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Actor updated with successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Actor.class))),
        
        @ApiResponse(responseCode = "404", description = "Actor not found") })
    @RequestMapping(value = "/actors/{actorId}",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Actor> updateActor(@Parameter(in = ParameterIn.PATH, description = "Actor's ID", required=true, schema=@Schema()) @PathVariable("actorId") Integer actorId
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Actor body
);

}

